node:
  host: localhost
  port: 2333

redis:
  host: "localhost"
  port: 6379
  secret: 'fishcakes'
  prefix: 'session'

ecg_api:
  url: 'http://dev.api.urlecg.com:2333'
  prefix: 'http://dev.api.urlecg.com:2333/v1'
  domain: 'http://dev.api.urlecg.com:3333'
  version: '0.0.1'



